on:
  push:
    branches:
      - main

jobs:
  create-and-update-api-endpoint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDS }}

      - uses: azure/cli@v2
        name: Azure CLI script

        with:
          azcliversion: latest
          inlineScript: |
            az apim api import -n ${{ secrets.APIM_INSTANCE }} -g ${{ secrets.APIM_RESOURCE_GROUP }} \
            --specification-format OpenApi \
            --specification-path ecommerce-organicos.yml \
            --path /ecommerce-organicos-alura \
            --api-revision  ${{ env.hash }}

